"""Update Default Balance

Revision ID: fb74aefff297
Revises: 7c428c87bddb
Create Date: 2022-11-10 00:09:11.178052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb74aefff297'
down_revision = '7c428c87bddb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_status', sa.String(), server_default='active', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'account_status')
    # ### end Alembic commands ###
